### ISSUE TITLE
panic crash and data loss after upstream restart and GetRecord

### ISSUE THREAD

**Issue by adam-olema** [fluent/fluent-bit-go#34]
```
panic: reflect: call of reflect.Value.Index on int64 Value

github.com/fluent/fluent-bit-go/output.GetRecord(0xc0004383d0, 0xc0000afc88, 0xc000401e60, 0x2b, 0xc0000afe00)
```

Scenario:

1) Very simple fluent-bit setup to receive from input.in_forward and output via my plugin:

```
    [SERVICE]
        Flush               5
        Log_Level           info
        Daemon              off
        Plugins_File        plugins.conf
        HTTP_Server         On
        HTTP_Listen         0.0.0.0
        HTTP_Port           2020

    [INPUT]
        Name                forward
        Host                0.0.0.0
        Port                24224
        Buffer_Chunk_Size   768KB

    [OUTPUT]
        Name                myplugin
        Match               *
        ...
```

2) When the upstream fluent-bit (the one with the output.out_forward) is restarted and starts sending data again, the receiver fluent-bit crashes completely (and loses the chunk of data it was trying to process completely) with:

```
[2020/06/11 22:04:36] [ info] [storage] version=1.0.3, initializing...
[2020/06/11 22:04:36] [ info] [storage] in-memory
[2020/06/11 22:04:36] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/06/11 22:04:36] [ info] [engine] started (pid=1)
[2020/06/11 22:04:36] [ info] [input:forward:forward.0] listening on 0.0.0.0:24224
2020/06/11 22:04:36 [output:myplugin] started
[2020/06/11 22:04:36] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2020/06/11 22:04:36] [ info] [sp] stream processor started
[2020/06/11 22:04:32] [ info] [engine] service stopped
panic: reflect: call of reflect.Value.Index on int64 Value

goroutine 17 [running, locked to thread]:
reflect.Value.Index(0x7f95fe42b5e0, 0xc0002f2d48, 0x86, 0x0, 0x0, 0x2b, 0x1)
        /usr/local/go/src/reflect/value.go:942 +0x1d2
github.com/fluent/fluent-bit-go/output.GetRecord(0xc0004383d0, 0xc0000afc88, 0xc000401e60, 0x2b, 0xc0000afe00)
        /go/src/github.com/fluent/fluent-bit-go/output/decoder.go:80 +0x10b
main.FLBPluginFlushCtx(0x7f95fec090d0, 0x7f95f59b6c40, 0xc00000cb65, 0x7f95fec3ef00, 0x28)
        /root/out_myplugin.go:89 +0x362
main._cgoexpwrap_971873ac4d50_FLBPluginFlushCtx(0x7f95fec090d0, 0x7f95f59b6c40, 0x55fd0000cb65, 0x7f95fec3ef00, 0x7f95feda2bb0)
        _cgo_gotypes.go:88 +0x49
```

3) The call to output.GetRecord in this stack trace and the code leading up to it is taken directly from the examples:

```
func FLBPluginFlushCtx(ctx, data unsafe.Pointer, length C.int, tag *C.char) int {
        logRoot := output.FLBPluginGetContext(ctx).(*ConfigContext).logRoot
        decoder := output.NewDecoder(data, int(length))
        logBatches := make(map[string]*LogBatch)

        for {
                ret, timestamp, record := output.GetRecord(decoder)
                if ret != 0 {
                        break
                }
```

I'm not super sure how to diagnose this, but it appears like the first packet of data coming in after the upstream restart is not what this framework is expecting.

**Comment by adam-olema** [comment]
Same panic, but different circumstance: https://github.com/fluent/fluent-bit-go/issues/29

**Comment by adam-olema** [comment]
This actually happens quite frequently in my production environment, even without restarts.

**Comment by edsiper** [comment]
@fluent/fluent-bit-maintainers

**Comment by adam-olema** [comment]
merged and tested
