### ISSUE TITLE
bug: panic: interface conversion: interface {} is []interface {} 

### ISSUE THREAD

**Issue by woehrl01** [fluent/fluent-bit-go#64]
I receive the following error, which results in a stuck crash loop

```bash
panic: interface conversion: interface {} is []interface {}, not map[interface {}]interface {}goroutine 17 [running, locked to thread]:github.com/fluent/fluent-bit-go/output.GetRecord(0xc000048000, 0xc000071c80, 0xc000018240, 0x28, 0xc0000f8128)	/go/pkg/mod/github.com/fluent/fluent-bit-go@v0.0.0-20200729034236-b9c0d6a20853/output/decoder.go:87 +0x2f5main.FLBPluginFlushCtx(0x7f5ad3a3b040, 0x7f5ad2fc5000, 0x99e, 0x7f5ad3a40240, 0x7f5aff7c5b86)	/go/src/github.com/newrelic/newrelic-fluent-bit-output/out_newrelic.go:59 +0x14bmain._cgoexpwrap_a6e139c81ab7_FLBPluginFlushCtx(0x7f5ad3a3b040, 0x7f5ad2fc5000, 0x55a17e0000099e, 0x7f5ad3a40240, 0x10000055a1)	_cgo_gotypes.go:75 +0x49
```

see https://github.com/newrelic/newrelic-fluent-bit-output/issues/126

**Comment by woehrl01** [comment]
Looks like it's related to that type assertion: https://github.com/fluent/fluent-bit-go/blob/master/output/decoder.go#L88
